// PoE1 gem vendor data from https://www.poewiki.net/wiki/List_of_vendor_rewards
// Format: { gemName: [ [act, quest, npc, [classes]] , ... ] }
// Only earliest availability per gem listed. Siosa (Act 3) sells ALL gems to ALL classes.
// After Act 6 "Fallen from Grace", Lily Roth sells ALL gems.

// act, quest, npc, classes (null = all classes)
const VENDOR_DATA = [
  // === Act 1: Enemy at the Gate (Nessa) ===
  ['Arcane Surge Support',1,'Enemy at the Gate','Nessa',['Witch']],
  ['Blight',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Scion']],
  ['Ethereal Knives',1,'Enemy at the Gate','Nessa',['Witch','Marauder','Shadow','Scion']],
  ['Explosive Trap',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Ranger','Scion']],
  ['Fireball',1,'Enemy at the Gate','Nessa',['Witch','Marauder','Scion']],
  ['Freezing Pulse',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Scion']],
  ['Frostbolt',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Scion']],
  ['Kinetic Bolt',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Ranger','Duelist','Scion']],
  ['Lightning Tendrils',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Marauder','Scion']],
  ['Purifying Flame',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Templar','Scion']],
  ['Raise Zombie',1,'Enemy at the Gate','Nessa',['Witch','Marauder','Templar','Scion']],
  ['Rolling Magma',1,'Enemy at the Gate','Nessa',['Witch','Marauder','Scion']],
  ['Spark',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Marauder','Scion']],
  ['Stormblast Mine',1,'Enemy at the Gate','Nessa',['Witch','Shadow','Marauder','Scion']],
  ['Prismatic Burst Support',1,'Enemy at the Gate','Nessa',null],
  ['Burning Arrow',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Scion']],
  ['Caustic Arrow',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Scion']],
  ['Chance to Poison Support',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Scion']],
  ['Cobra Lash',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Scion']],
  ['Double Strike',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Marauder','Scion']],
  ['Dual Strike',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Marauder','Scion']],
  ['Frost Blades',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Scion']],
  ['Viper Strike',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Marauder','Scion']],
  ['Spectral Throw',1,'Enemy at the Gate','Nessa',['Shadow','Ranger','Duelist','Marauder','Templar','Scion']],
  ['Split Arrow',1,'Enemy at the Gate','Nessa',['Ranger','Duelist','Scion']],
  ['Cleave',1,'Enemy at the Gate','Nessa',['Ranger','Duelist','Marauder','Scion']],
  ['Galvanic Arrow',1,'Enemy at the Gate','Nessa',['Ranger','Duelist','Scion']],
  ['Ice Shot',1,'Enemy at the Gate','Nessa',['Ranger','Duelist','Scion']],
  ['Momentum Support',1,'Enemy at the Gate','Nessa',['Ranger','Duelist','Scion']],
  ['Perforate',1,'Enemy at the Gate','Nessa',['Ranger','Duelist','Marauder','Scion']],
  ['Splitting Steel',1,'Enemy at the Gate','Nessa',['Ranger','Duelist','Scion']],
  ['Chance to Bleed Support',1,'Enemy at the Gate','Nessa',['Duelist','Marauder','Scion']],
  ['Glacial Hammer',1,'Enemy at the Gate','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Ground Slam',1,'Enemy at the Gate','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Heavy Strike',1,'Enemy at the Gate','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Molten Strike',1,'Enemy at the Gate','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Shield Crush',1,'Enemy at the Gate','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Ruthless Support',1,'Enemy at the Gate','Nessa',['Marauder','Templar','Scion']],
  ['Smite',1,'Enemy at the Gate','Nessa',['Marauder','Templar','Scion']],
  ['Elemental Proliferation Support',1,'Enemy at the Gate','Nessa',['Templar','Scion']],

  // === Act 1: The Caged Brute (Nessa) ===
  ['Clarity',1,'The Caged Brute','Nessa',['Witch']],
  ['Melee Splash Support',1,'The Caged Brute','Nessa',['Witch']],
  ['Precision',1,'The Caged Brute','Nessa',['Witch']],
  ['Vitality',1,'The Caged Brute','Nessa',['Witch']],
  ['Added Cold Damage Support',1,'The Caged Brute','Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Added Lightning Damage Support',1,'The Caged Brute','Nessa',['Shadow','Ranger','Marauder','Templar','Scion']],
  ['Blastchain Mine Support',1,'The Caged Brute','Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Bodyswap',1,'The Caged Brute','Nessa',null],
  ['Combustion Support',1,'The Caged Brute','Nessa',null],
  ['Devour Support',1,'The Caged Brute','Nessa',null],
  ['Efficacy Support',1,'The Caged Brute','Nessa',null],
  ['Flame Dash',1,'The Caged Brute','Nessa',null],
  ['Increased Critical Strikes Support',1,'The Caged Brute','Nessa',null],
  ['Infernal Legion Support',1,'The Caged Brute','Nessa',['Shadow','Marauder','Templar','Scion']],
  ['Lightning Warp',1,'The Caged Brute','Nessa',null],
  ['Locus Mine Support',1,'The Caged Brute','Nessa',null],
  ['Minion Damage Support',1,'The Caged Brute','Nessa',['Shadow','Marauder','Templar','Scion']],
  ['Multiple Projectiles Support',1,'The Caged Brute','Nessa',null],
  ['Multiple Traps Support',1,'The Caged Brute','Nessa',null],
  ['Siphoning Trap',1,'The Caged Brute','Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Smoke Mine',1,'The Caged Brute','Nessa',null],
  ['Spell Totem Support',1,'The Caged Brute','Nessa',['Shadow','Marauder','Templar','Scion']],
  ['Summon Skeletons',1,'The Caged Brute','Nessa',['Shadow','Marauder','Templar','Scion']],
  ['Trap Support',1,'The Caged Brute','Nessa',null],
  ['Unbound Ailments Support',1,'The Caged Brute','Nessa',['Shadow','Marauder','Templar','Scion']],
  ['Unearth',1,'The Caged Brute','Nessa',null],
  ['Void Manipulation Support',1,'The Caged Brute','Nessa',['Shadow','Marauder','Templar','Scion']],
  ['Wither',1,'The Caged Brute','Nessa',['Shadow','Marauder','Templar','Scion']],
  ['Withering Step',1,'The Caged Brute','Nessa',null],
  ['Added Fire Damage Support',1,'The Caged Brute','Nessa',null],
  ['Additional Accuracy Support',1,'The Caged Brute','Nessa',null],
  ['Arrow Nova Support',1,'The Caged Brute','Nessa',null],
  ['Ballista Totem Support',1,'The Caged Brute','Nessa',null],
  ['Blind Support',1,'The Caged Brute','Nessa',null],
  ['Blink Arrow',1,'The Caged Brute','Nessa',null],
  ['Chance to Flee Support',1,'The Caged Brute','Nessa',null],
  ['Faster Attacks Support',1,'The Caged Brute','Nessa',null],
  ['Flicker Strike',1,'The Caged Brute','Nessa',null],
  ['Manaforged Arrows Support',1,'The Caged Brute','Nessa',null],
  ['Whirling Blades',1,'The Caged Brute','Nessa',null],
  ['Leap Slam',1,'The Caged Brute','Nessa',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Maim Support',1,'The Caged Brute','Nessa',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Enduring Cry',1,'The Caged Brute','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Intimidating Cry',1,'The Caged Brute','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Knockback Support',1,'The Caged Brute','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Life Gain on Hit Support',1,'The Caged Brute','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Lifetap Support',1,'The Caged Brute','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Stun Support',1,'The Caged Brute','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Flamewood Support',1,'The Caged Brute','Nessa',['Marauder','Templar','Scion']],

  // === Act 1: The Siren's Cadence (Nessa) ===
  ['Absolution',1,"The Siren's Cadence",'Nessa',['Witch','Templar','Scion']],
  ['Arc',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Blade Vortex',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Blazing Salvo',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Bone Offering',1,"The Siren's Cadence",'Nessa',['Witch','Templar','Scion']],
  ['Creeping Frost',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Essence Drain',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Exsanguinate',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Fire Trap',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Flame Surge',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Flesh Offering',1,"The Siren's Cadence",'Nessa',['Witch','Templar','Scion']],
  ['Ice Nova',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Ice Spear',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Icicle Mine',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Incinerate',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Kinetic Fusillade',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Lightning Trap',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Manabond',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Power Siphon',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Scorching Ray',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Searing Bond',1,"The Siren's Cadence",'Nessa',['Witch','Templar','Scion']],
  ['Spirit Offering',1,"The Siren's Cadence",'Nessa',['Witch','Templar','Scion']],
  ['Storm Brand',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Storm Burst',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Storm Call',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Volatile Dead',1,"The Siren's Cadence",'Nessa',['Witch','Templar','Scion']],
  ['Voltaxic Burst',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Wintertide Brand',1,"The Siren's Cadence",'Nessa',['Witch','Shadow','Templar','Scion']],
  ['Barrage',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Blade Trap',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Elemental Hit',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Lacerate',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Lightning Arrow',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Lightning Strike',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Poisonous Concoction',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Rain of Arrows',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Reave',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Shattering Steel',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Siege Ballista',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Spectral Helix',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Static Strike',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Toxic Rain',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Venom Gyre',1,"The Siren's Cadence",'Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Infernal Blow',1,"The Siren's Cadence",'Nessa',['Ranger','Duelist','Templar','Scion']],
  ['Chain Hook',1,"The Siren's Cadence",'Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Earthshatter',1,"The Siren's Cadence",'Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Holy Sweep',1,"The Siren's Cadence",'Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Sunder',1,"The Siren's Cadence",'Nessa',['Duelist','Marauder','Templar','Scion']],

  // === Act 1: Breaking Some Eggs (Nessa) ===
  ['Dash',1,'Breaking Some Eggs','Nessa',['Witch','Shadow','Ranger']],
  ['Frostblink',1,'Breaking Some Eggs','Nessa',['Witch','Shadow','Ranger']],
  ['Shield Charge',1,'Breaking Some Eggs','Nessa',['Shadow','Ranger','Duelist']],
  ['Animate Weapon',1,'Breaking Some Eggs','Nessa',null],
  ['Contagion',1,'Breaking Some Eggs','Nessa',null],
  ['Conversion Trap',1,'Breaking Some Eggs','Nessa',null],
  ['Detonate Dead',1,'Breaking Some Eggs','Nessa',null],
  ['Devouring Totem',1,'Breaking Some Eggs','Nessa',['Witch','Duelist','Marauder','Templar','Scion']],
  ['Flame Wall',1,'Breaking Some Eggs','Nessa',null],
  ['Frost Bomb',1,'Breaking Some Eggs','Nessa',null],
  ['Frost Wall',1,'Breaking Some Eggs','Nessa',['Witch','Duelist','Marauder','Templar','Scion']],
  ['Holy Flame Totem',1,'Breaking Some Eggs','Nessa',['Witch','Marauder','Templar','Scion']],
  ['Orb of Storms',1,'Breaking Some Eggs','Nessa',null],
  ['Summon Holy Relic',1,'Breaking Some Eggs','Nessa',['Witch','Templar','Scion']],
  ['Summon Raging Spirit',1,'Breaking Some Eggs','Nessa',null],
  ['Bear Trap',1,'Breaking Some Eggs','Nessa',null],
  ['Blood and Sand',1,'Breaking Some Eggs','Nessa',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Decoy Totem',1,'Breaking Some Eggs','Nessa',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Puncture',1,'Breaking Some Eggs','Nessa',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Shrapnel Ballista',1,'Breaking Some Eggs','Nessa',null],
  ["Sniper's Mark",1,'Breaking Some Eggs','Nessa',null],
  ['Vigilant Strike',1,'Breaking Some Eggs','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['War Banner',1,'Breaking Some Eggs','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Crushing Fist',1,'Breaking Some Eggs','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Rejuvenation Totem',1,'Breaking Some Eggs','Nessa',['Duelist','Marauder','Templar','Scion']],
  ['Steelskin',1,'Breaking Some Eggs','Nessa',['Duelist','Marauder','Templar','Scion']],

  // === Act 1: Mercy Mission (Nessa) ===
  ['Infused Channelling Support',1,'Mercy Mission','Nessa',['Witch','Marauder','Templar','Scion']],
  ['Spell Cascade Support',1,'Mercy Mission','Nessa',['Witch','Shadow','Templar','Scion']],
  ['Summon Phantasm Support',1,'Mercy Mission','Nessa',['Witch','Marauder','Templar','Scion']],
  ['Swift Assembly Support',1,'Mercy Mission','Nessa',null],
  ['Volley Support',1,'Mercy Mission','Nessa',null],
  ['Mirage Archer Support',1,'Mercy Mission','Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Pierce Support',1,'Mercy Mission','Nessa',['Shadow','Ranger','Duelist','Templar','Scion']],
  ['Ancestral Call Support',1,'Mercy Mission','Nessa',['Ranger','Duelist','Marauder','Templar','Scion']],

  // === Act 2: Sharp and Cruel (Yeena) ===
  ['Culling Strike Support',2,'Sharp and Cruel','Yeena',['Witch']],
  ['Melee Physical Damage Support',2,'Sharp and Cruel','Yeena',['Witch']],
  ['Sadism Support',2,'Sharp and Cruel','Yeena',['Witch']],
  ['Cold to Fire Support',2,'Sharp and Cruel','Yeena',null],
  ['Concentrated Effect Support',2,'Sharp and Cruel','Yeena',null],
  ['Controlled Destruction Support',2,'Sharp and Cruel','Yeena',null],
  ['Cruelty Support',2,'Sharp and Cruel','Yeena',null],
  ['Deadly Ailments Support',2,'Sharp and Cruel','Yeena',null],
  ['Elemental Focus Support',2,'Sharp and Cruel','Yeena',null],
  ['Faster Casting Support',2,'Sharp and Cruel','Yeena',null],
  ['Fresh Meat Support',2,'Sharp and Cruel','Yeena',['Shadow','Marauder','Templar','Scion']],
  ['Increased Critical Damage Support',2,'Sharp and Cruel','Yeena',null],
  ['Kinetic Instability Support',2,'Sharp and Cruel','Yeena',null],
  ['Living Lightning Support',2,'Sharp and Cruel','Yeena',['Shadow','Marauder','Templar','Scion']],
  ['Minion Life Support',2,'Sharp and Cruel','Yeena',['Shadow','Marauder','Templar','Scion']],
  ['Minion Speed Support',2,'Sharp and Cruel','Yeena',null],
  ['Overcharge Support',2,'Sharp and Cruel','Yeena',null],
  ['Power Charge On Critical Support',2,'Sharp and Cruel','Yeena',null],
  ['Predator Support',2,'Sharp and Cruel','Yeena',['Shadow','Marauder','Templar','Scion']],
  ['Sacred Wisps Support',2,'Sharp and Cruel','Yeena',null],
  ['Trap and Mine Damage Support',2,'Sharp and Cruel','Yeena',null],
  ['Trinity Support',2,'Sharp and Cruel','Yeena',null],
  ['Bloodlust Support',2,'Sharp and Cruel','Yeena',null],
  ['Close Combat Support',2,'Sharp and Cruel','Yeena',null],
  ['Elemental Damage with Attacks Support',2,'Sharp and Cruel','Yeena',null],
  ['Nightblade Support',2,'Sharp and Cruel','Yeena',null],
  ['Physical to Lightning Support',2,'Sharp and Cruel','Yeena',null],
  ['Point Blank Support',2,'Sharp and Cruel','Yeena',null],
  ['Rage Support',2,'Sharp and Cruel','Yeena',null],
  ['Iron Grip Support',2,'Sharp and Cruel','Yeena',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Vicious Projectiles Support',2,'Sharp and Cruel','Yeena',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Damage on Full Life Support',2,'Sharp and Cruel','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Endurance Charge on Melee Stun Support',2,'Sharp and Cruel','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Iron Will Support',2,'Sharp and Cruel','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Shockwave Support',2,'Sharp and Cruel','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Volatility Support',2,'Sharp and Cruel','Yeena',['Duelist','Marauder','Templar','Scion']],

  // === Act 2: Intruders in Black (Yeena) ===
  ['Herald of Ash',2,'Intruders in Black','Yeena',['Witch']],
  ['Herald of Ice',2,'Intruders in Black','Yeena',['Witch']],
  ['Herald of Thunder',2,'Intruders in Black','Yeena',['Witch']],
  ['Arcane Cloak',2,'Intruders in Black','Yeena',['Witch','Shadow','Templar','Scion']],
  ['Arctic Armour',2,'Intruders in Black','Yeena',null],
  ['Blade Blast',2,'Intruders in Black','Yeena',['Witch','Shadow','Ranger','Duelist','Templar','Scion']],
  ['Brand Recall',2,'Intruders in Black','Yeena',['Witch','Marauder','Templar','Scion']],
  ['Cold Snap',2,'Intruders in Black','Yeena',null],
  ['Desecrate',2,'Intruders in Black','Yeena',['Witch','Shadow','Marauder','Templar','Scion']],
  ['Divine Retribution',2,'Intruders in Black','Yeena',['Witch','Templar','Scion']],
  ['Forbidden Rite',2,'Intruders in Black','Yeena',['Witch','Shadow','Marauder','Templar','Scion']],
  ['Galvanic Field',2,'Intruders in Black','Yeena',['Witch','Shadow','Marauder','Templar','Scion']],
  ['Herald of Purity',2,'Intruders in Black','Yeena',['Witch','Duelist','Marauder','Templar','Scion']],
  ['Righteous Fire',2,'Intruders in Black','Yeena',['Witch','Marauder','Templar','Scion']],
  ['Summon Skitterbots',2,'Intruders in Black','Yeena',['Witch','Shadow','Marauder','Templar','Scion']],
  ['Tempest Shield',2,'Intruders in Black','Yeena',['Witch','Shadow','Duelist','Marauder','Templar','Scion']],
  ['Wall of Force',2,'Intruders in Black','Yeena',['Witch','Shadow','Templar','Scion']],
  ['Wave of Conviction',2,'Intruders in Black','Yeena',['Witch','Shadow','Templar','Scion']],
  ["Assassin's Mark",2,'Intruders in Black','Yeena',null],
  ['Blood Rage',2,'Intruders in Black','Yeena',null],
  ['Ensnaring Arrow',2,'Intruders in Black','Yeena',null],
  ['Frenzy',2,'Intruders in Black','Yeena',null],
  ['Herald of Agony',2,'Intruders in Black','Yeena',null],
  ["Poacher's Mark",2,'Intruders in Black','Yeena',null],
  ['Glacial Shield Swipe',2,'Intruders in Black','Yeena',['Ranger','Duelist','Marauder','Templar','Scion']],
  ["Warlord's Mark",2,'Intruders in Black','Yeena',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Ancestral Cry',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Corrupting Fever',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Defiance Banner',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Eviscerate',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Flesh and Stone',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Molten Shell',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Seismic Cry',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Swordstorm',2,'Intruders in Black','Yeena',['Duelist','Marauder','Templar','Scion']],
  ['Plague Bearer',2,'The Root of the Problem','Yeena',['Duelist','Marauder','Templar','Scion']],

  // === Act 3: Lost in Love (Clarissa) ===
  ['Automation',3,'Lost in Love','Clarissa',['Witch']],
  ['Pride',3,'Lost in Love','Clarissa',['Witch']],
  ['Purity of Elements',3,'Lost in Love','Clarissa',['Witch']],
  ['Bane',3,'Lost in Love','Clarissa',['Witch','Shadow','Templar','Scion']],
  ['Conductivity',3,'Lost in Love','Clarissa',['Witch','Shadow','Duelist','Marauder','Templar','Scion']],
  ['Despair',3,'Lost in Love','Clarissa',['Witch','Shadow','Marauder','Templar','Scion']],
  ['Discipline',3,'Lost in Love','Clarissa',['Witch','Shadow','Templar','Scion']],
  ['Elemental Weakness',3,'Lost in Love','Clarissa',null],
  ['Energy Blade',3,'Lost in Love','Clarissa',['Witch','Shadow','Templar','Scion']],
  ['Enfeeble',3,'Lost in Love','Clarissa',null],
  ['Flammability',3,'Lost in Love','Clarissa',['Witch','Shadow','Templar','Scion']],
  ['Frostbite',3,'Lost in Love','Clarissa',null],
  ['Hatred',3,'Lost in Love','Clarissa',null],
  ['Malevolence',3,'Lost in Love','Clarissa',['Witch','Shadow','Marauder','Templar','Scion']],
  ['Purity of Lightning',3,'Lost in Love','Clarissa',['Witch','Shadow','Templar','Scion']],
  ['Spellslinger',3,'Lost in Love','Clarissa',['Witch','Shadow','Templar','Scion']],
  ['Temporal Chains',3,'Lost in Love','Clarissa',null],
  ['Wrath',3,'Lost in Love','Clarissa',['Witch','Shadow','Marauder','Templar','Scion']],
  ['Zealotry',3,'Lost in Love','Clarissa',['Witch','Shadow','Templar','Scion']],
  ["Alchemist's Mark",3,'Lost in Love','Clarissa',null],
  ['Grace',3,'Lost in Love','Clarissa',null],
  ['Haste',3,'Lost in Love','Clarissa',null],
  ['Purity of Ice',3,'Lost in Love','Clarissa',null],
  ['Anger',3,'Lost in Love','Clarissa',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Dread Banner',3,'Lost in Love','Clarissa',['Ranger','Duelist','Marauder','Templar','Scion']],
  ['Autoexertion',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ["Battlemage's Cry",3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Determination',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ["General's Cry",3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Infernal Cry',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Petrified Blood',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Punishment',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Purity of Fire',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Rallying Cry',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Vengeful Cry',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],
  ['Vulnerability',3,'Lost in Love','Clarissa',['Duelist','Marauder','Templar','Scion']],

  // === Act 3: A Fixture of Fate (Siosa) — sells ALL gems to ALL classes ===
  // Only listing gems that first appear here (not available from earlier quests)
  ['Animate Guardian',3,'A Fixture of Fate','Siosa',null],
  ['Armageddon Brand',3,'A Fixture of Fate','Siosa',null],
  ['Artillery Ballista',3,'A Fixture of Fate','Siosa',null],
  ['Ball Lightning',3,'A Fixture of Fate','Siosa',null],
  ['Blade Flurry',3,'A Fixture of Fate','Siosa',null],
  ['Bladefall',3,'A Fixture of Fate','Siosa',null],
  ['Bladestorm',3,'A Fixture of Fate','Siosa',null],
  ['Blast Rain',3,'A Fixture of Fate','Siosa',null],
  ['Boneshatter',3,'A Fixture of Fate','Siosa',null],
  ['Charged Dash',3,'A Fixture of Fate','Siosa',null],
  ['Conflagration',3,'A Fixture of Fate','Siosa',null],
  ['Consecrated Path',3,'A Fixture of Fate','Siosa',null],
  ['Cyclone',3,'A Fixture of Fate','Siosa',null],
  ['Dark Pact',3,'A Fixture of Fate','Siosa',null],
  ['Divine Ire',3,'A Fixture of Fate','Siosa',null],
  ['Dominating Blow',3,'A Fixture of Fate','Siosa',null],
  ['Earthquake',3,'A Fixture of Fate','Siosa',null],
  ['Eye of Winter',3,'A Fixture of Fate','Siosa',null],
  ['Firestorm',3,'A Fixture of Fate','Siosa',null],
  ['Flameblast',3,'A Fixture of Fate','Siosa',null],
  ['Flamethrower Trap',3,'A Fixture of Fate','Siosa',null],
  ['Glacial Cascade',3,'A Fixture of Fate','Siosa',null],
  ['Hexblast',3,'A Fixture of Fate','Siosa',null],
  ['Ice Crash',3,'A Fixture of Fate','Siosa',null],
  ['Ice Trap',3,'A Fixture of Fate','Siosa',null],
  ['Kinetic Blast',3,'A Fixture of Fate','Siosa',null],
  ['Kinetic Rain',3,'A Fixture of Fate','Siosa',null],
  ['Lancing Steel',3,'A Fixture of Fate','Siosa',null],
  ['Lightning Spire Trap',3,'A Fixture of Fate','Siosa',null],
  ['Mirror Arrow',3,'A Fixture of Fate','Siosa',null],
  ['Penance Brand',3,'A Fixture of Fate','Siosa',null],
  ['Pestilent Strike',3,'A Fixture of Fate','Siosa',null],
  ['Pyroclast Mine',3,'A Fixture of Fate','Siosa',null],
  ['Rage Vortex',3,'A Fixture of Fate','Siosa',null],
  ['Raise Spectre',3,'A Fixture of Fate','Siosa',null],
  ['Reap',3,'A Fixture of Fate','Siosa',null],
  ['Scourge Arrow',3,'A Fixture of Fate','Siosa',null],
  ['Seismic Trap',3,'A Fixture of Fate','Siosa',null],
  ['Shock Nova',3,'A Fixture of Fate','Siosa',null],
  ['Shockwave Totem',3,'A Fixture of Fate','Siosa',null],
  ['Somatic Shell',3,'A Fixture of Fate','Siosa',null],
  ['Soulrend',3,'A Fixture of Fate','Siosa',null],
  ['Spectral Shield Throw',3,'A Fixture of Fate','Siosa',null],
  ['Storm Rain',3,'A Fixture of Fate','Siosa',null],
  ['Stormbind',3,'A Fixture of Fate','Siosa',null],
  ['Tornado Shot',3,'A Fixture of Fate','Siosa',null],
  ['Winter Orb',3,'A Fixture of Fate','Siosa',null],
  ['Summon Carrion Golem',3,'A Fixture of Fate','Siosa',null],
  ['Summon Stone Golem',3,'A Fixture of Fate','Siosa',null],
  ['Summon Chaos Golem',3,'A Fixture of Fate','Siosa',null],
  ['Summon Flame Golem',3,'A Fixture of Fate','Siosa',null],
  ['Summon Ice Golem',3,'A Fixture of Fate','Siosa',null],
  ['Summon Lightning Golem',3,'A Fixture of Fate','Siosa',null],
  ['Tectonic Slam',3,'A Fixture of Fate','Siosa',null],
  ['Phase Run',3,'A Fixture of Fate','Siosa',null],
  ['Blasphemy Support',3,'A Fixture of Fate','Siosa',null],
  ['Generosity Support',3,'A Fixture of Fate','Siosa',null],
  ['Spell Echo Support',3,'A Fixture of Fate','Siosa',null],
  ['Multistrike Support',3,'A Fixture of Fate','Siosa',null],
  ['Greater Multiple Projectiles Support',3,'A Fixture of Fate','Siosa',null],
  ['Chain Support',3,'A Fixture of Fate','Siosa',null],
  ['Fork Support',3,'A Fixture of Fate','Siosa',null],
  ['Cluster Trap Support',3,'A Fixture of Fate','Siosa',null],
  ['Brutality Support',3,'A Fixture of Fate','Siosa',null],
  ['Feeding Frenzy Support',3,'A Fixture of Fate','Siosa',null],
  ['Impale Support',3,'A Fixture of Fate','Siosa',null],
  ['Pulverise Support',3,'A Fixture of Fate','Siosa',null],
  ['Inspiration Support',3,'A Fixture of Fate','Siosa',null],
  ['Unleash Support',3,'A Fixture of Fate','Siosa',null],
  ['Intensify Support',3,'A Fixture of Fate','Siosa',null],
  ['Energy Leech Support',3,'A Fixture of Fate','Siosa',null],
  ['Hextouch Support',3,'A Fixture of Fate','Siosa',null],
  ['Cast when Damage Taken Support',3,'A Fixture of Fate','Siosa',null],
  ['Cast on Critical Strike Support',3,'A Fixture of Fate','Siosa',null],
  ['Immortal Call',3,'A Fixture of Fate','Siosa',null],
  ['Empower Support',3,'A Fixture of Fate','Siosa',null],
  ['Enlighten Support',3,'A Fixture of Fate','Siosa',null],
  ['Enhance Support',3,'A Fixture of Fate','Siosa',null],
  ['Added Chaos Damage Support',3,'A Fixture of Fate','Siosa',null],
  ['Hypothermia Support',3,'A Fixture of Fate','Siosa',null],
  ['Ice Bite Support',3,'A Fixture of Fate','Siosa',null],
  ['Innervate Support',3,'A Fixture of Fate','Siosa',null],
  ['Melee Splash Support',3,'A Fixture of Fate','Siosa',null],
  ['Culling Strike Support',3,'A Fixture of Fate','Siosa',null],
  ['Discharge',3,'A Fixture of Fate','Siosa',null],
  ['Portal',3,'A Fixture of Fate','Siosa',null],
];

// Build lookup: gem name → earliest entry per class
// { gemName: { act, quest, npc, classes } }
const GEM_LOOKUP = {};
for (const [name, act, quest, npc, classes] of VENDOR_DATA) {
  if (!GEM_LOOKUP[name]) {
    GEM_LOOKUP[name] = { act, quest, npc, classes };
  }
  // Keep earliest act
  if (act < GEM_LOOKUP[name].act) {
    GEM_LOOKUP[name] = { act, quest, npc, classes };
  }
}

/**
 * Get vendor source for a gem, considering the build's class and whether
 * the setup is early game (pre-Act 6).
 * @param {string} gemName
 * @param {string} className - the build's class
 * @param {boolean} isEarlyGame - true if setup is pre-Act 6
 * @returns {{ text: string, detail: string }}
 */
export function getGemSource(gemName, className, isEarlyGame) {
  const info = GEM_LOOKUP[gemName];
  if (!info) {
    return { text: 'Lily (A6)', detail: 'Lily Roth - Fallen from Grace (Act 6)' };
  }

  // Check if your class can get it from the earliest source
  const classHasAccess = !info.classes || info.classes.includes(className);

  if (classHasAccess) {
    return {
      text: `${info.npc} (A${info.act})`,
      detail: `${info.npc} - ${info.quest} (Act ${info.act})`,
    };
  }

  // Class can't get it from earliest vendor — Siosa (Act 3) sells all to all classes
  return { text: 'Siosa (A3)', detail: 'Siosa - A Fixture of Fate (Act 3)' };
}
